//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyKeKhaiGiangDayCuaGiangVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DotKeKhai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DotKeKhai()
        {
            this.KeKhais = new HashSet<KeKhai>();
            this.PhanCongHocPhans = new HashSet<PhanCongHocPhan>();
        }
    
        public int MaDotKeKhai { get; set; }
        public string TenDotKeKhai { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string MaGV { get; set; }
        public Nullable<bool> KeKhaiMoi { get; set; }
        public string GhiChu { get; set; }
        public int MaHocKy { get; set; }
        public int MaNamHoc { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual HocKy HocKy { get; set; }
        public virtual NamHoc NamHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeKhai> KeKhais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCongHocPhan> PhanCongHocPhans { get; set; }
    }
}
