//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyKeKhaiGiangDayCuaGiangVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocPhan()
        {
            this.PhanCongHocPhans = new HashSet<PhanCongHocPhan>();
        }
    
        public string MaHP { get; set; }
        public string TenHP { get; set; }
        public Nullable<int> SoTinChi { get; set; }
        public Nullable<int> LyThuyet { get; set; }
        public Nullable<int> ThucHanh { get; set; }
        public string MoTa { get; set; }
        public bool IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCongHocPhan> PhanCongHocPhans { get; set; }
    }
}
