//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyKeKhaiGiangDayCuaGiangVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeKhai
    {
        public int MaKeKhai { get; set; }
        public string MaGV { get; set; }
        public int MaPhanCongHocPhan { get; set; }
        public int MaDotKeKhai { get; set; }
        public System.DateTime NgayKeKhai { get; set; }
        public Nullable<System.DateTime> NgayDuyetKeKhai { get; set; }
        public string idNguoiDuyet { get; set; }
    
        public virtual DotKeKhai DotKeKhai { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        public virtual GiangVien GiangVien1 { get; set; }
        public virtual PhanCongHocPhan PhanCongHocPhan { get; set; }
    }
}
