//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyKeKhaiGiangDayCuaGiangVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int RolePermission1 { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> PermissionId { get; set; }
    
        public virtual Quyen Quyen { get; set; }
        public virtual Role Role { get; set; }
    }
}
