//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyKeKhaiGiangDayCuaGiangVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeChiTiet
    {
        public int Id { get; set; }
        public int MaThongKe { get; set; }
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public string TenKhoa { get; set; }
        public Nullable<int> SoLuongPhanCong { get; set; }
        public Nullable<int> DaThuHien { get; set; }
    
        public virtual ThongKe ThongKe { get; set; }
    }
}
